<?xml version="1.0"?>
<package format="3">
  <name>hakoniwa_arm_samples</name>
  <version>0.1.0</version>
  <description>Robot-independent ROS 2 control and monitoring samples for Hakoniwa robot arms.</description>
  <maintainer email="tmori@hakoniwa-lab.net">tmori</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>trajectory_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
